### PR TITLE
Containerise app

### LINKED ISSUE #11: Containerise Project
Hey guys, some lovely stuff here.

I was trying to set up and it seemed this could use some containerisation.

A dockerfile and docker-compose files for redis, postgres, etc?

I could set this up over the weekend.

Great work this.

### PR DESCRIPTION
**Pull request by oneEyedSunday**
Closes #11 

I need some input though. 
I get this error
```sh
postmates-postgres | 2021-01-23 15:13:25.137 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postmates-postgres | 2021-01-23 15:13:25.138 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postmates-postgres | 2021-01-23 15:13:25.153 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postmates-postgres | 2021-01-23 15:13:25.174 UTC [27] LOG:  database system was shut down at 2021-01-23 15:11:52 UTC
postmates-postgres | 2021-01-23 15:13:25.183 UTC [1] LOG:  database system is ready to accept connections
postmates-app | docker-compose-wait - Everything's fine, the application can now start!
postmates-app | --------------------------------------------------------
postmates-app | Omo this is path: /appPath to seedProducts is: /apppanic: open /app/database/products.yml: no such file or directory
postmates-app | 
postmates-app | goroutine 1 [running]:
postmates-app | github.com/gwuah/postmates/database.SeedProducts(0xc000186db0, 0xc0000340b4, 0x4)
postmates-app | 	/app/database/seeds.go:33 +0x502
postmates-app | github.com/gwuah/postmates/database.RunSeeds(0xc000186db0, 0xc000425e60, 0x4, 0x4)
postmates-app | 	/app/database/seeds.go:25 +0x113
postmates-app | main.main()
postmates-app | 	/app/main.go:57 +0x5e9
postmates-app exited with code 2

```

Seems there's some path-based approach I'm unable to replicate in the container in the `seeds.go` file.
I'd expect `yaml.ReadFile` to be able to read files without a fully qualified path? like so `./products.yaml`?

### CODE REVIEW

**Comment by oneEyedSunday** [comment]
Ok, figured this out. :)

I'm using a multi stage build to reduce the container size.

I forgot to also copy the database/** files

**Comment by oneEyedSunday** [comment]
Ok, this is ready now.

**Comment by oneEyedSunday** [comment]
Hey bro @gwuah 
I'd have to set up db schema migrations before this can realistically be merged in.
Should get some time to do that within the week.

**Comment by gwuah** [comment]
@oneEyedSunday how far, chief?

**Comment by oneEyedSunday** [comment]
Sorry. Got caught up in some stuff. Should get it done over the weekend. 😩
Not had electricity since last week.

**Comment by oneEyedSunday** [comment]
So the schema actually gets created 
https://github.com/gwuah/postmates/issues/13#issuecomment-787543616
Screenshot 2021-03-01 at 00 18 11

So this is ready to go.

**Review by gwuah — APPROVED** [review]

**Pull request merged**
